### ISSUE TITLE
Question about verification

### ISSUE THREAD

**Issue by stsch9** [jedisct1/libsodium-signcryption#6]
I have a question: Only the ciphertext and not the plaintext is used for verification. So if the verification fails, the ciphertext does not have to be decrypted at all. This is an advantage over signcryption schemes, which are described in https://www.itiis.org/digital-library/manuscript/2298, for example. Would the following sequence therefore make sense? 

1.  crypto_signcrypt_tbsbr_verify_before()
2. crypto_signcrypt_tbsbr_verify_after() - The return of that function must be checked.
3. decrypt with shared_key

**Comment by jedisct1** [comment]
The documentation recommends decryption before the signature verification:
- For clarity (symmetry with the signcryption procedure)
- For short messages, checking the AEAD authentication tag is faster than the signature, so this is less prone to DoS attacks (otherwise, any gibberish will still require a scalar multiplication).
- The shared secret can be immediately wiped from memory.

But of course, you can do it the other way round.

**Comment by stsch9** [comment]
Thank you for the answer!
